### ISSUE TITLE
[RFC] The Future of Next Starter Tailwind

### ISSUE THREAD

**Issue by taylorbryant** [taylorbryant/next-starter-tailwind#100]
Hey, reader! 👋 I’ve been thinking a lot lately about where I want to go with this starter in the future. I initially created the starter, because I wasn’t satisfied with the example in the Next.js repository. Over the past year, contributions from myself and other people have made the example more or less in line with what I provide in this starter.

So... now I’m working what I can add to this starter that would add value past what’s already in the `with-tailwindcss` example in the Next.js repo. 

Here’s some ideas I have:
- Add fully fleshed-out example pages like:
    - A landing page for a SaaS app
    - A landing page for a brick-and-mortar business
    - An app dashboard 
    - A sign-in page for a SaaS app
    - An edit profile page for a SaaS app
    - A sign-up page for a SaaS app
- Add Prettier with the default settings
- Add documentation on how to use the starter with Tailwind UI
- Add ESLint with the following plugins:
    - `eslint-plugin-import`
    - `eslint-plugin-react`
    - `eslint-plugin-react-hooks`
    - `eslint-plugin-prettier`
- Add `husky` and `lint-staged` and do the following on every commit:
   - Fix linting errors
   - Format using Prettier
   - Sort Tailwind CSS classes using `rustywind`
   - Sort imports using `import-sort`

Some questions I have for you:
1. Do you think baking in opinions like these would be useful to you when starting a new project that uses Tailwind CSS and Next.js?
2. What ideas seem good to you? Which ones seem bad?
3. What’s something you might find useful in this starter that’s missing?
4. What kind of examples would you like to see added?

Thanks for your time! 👍🏻

**Comment by Jensderond** [comment]
I would love all the prettier config's to be in a starter project, also wouldn't mind to have Typescript baked in!

**Comment by krystian-mw** [comment]
Hi, I know this couple of months old but is this still someting you are maintaining? If so, I would be more than happy to help and contribute as I see this template to be the foundation of my future projects

**Comment by taylorbryant** [comment]
@krystian-mw Yes, I'm still actively maintaining the project. I plan to start on the next iteration here soon! I'm going to open some issues for all of the things mentioned in this issue. Once I do that, you're welcome to tackle any of them you want! Contributions are welcome! I appreciate you.

**Comment by tmoran18** [comment]
@taylorbryant I have been using Next for a few months, and would like to start getting into learning Tailwind. I was hoping to contribute by starting with one of the fully fleshed-out example pages.

I would design it up in Figma first, submit the design for approval maybe? Then start on development if that suited you?

I think maybe a discussion about how to best structure starters also. You don't want to have to delete to much out of a starter, I think Nextjs does a good job with their massive example of starters, but maybe adding a little more polish?
