### ISSUE TITLE
A next-tailwind-emotion starter

### ISSUE THREAD

**Issue by theairbend3r** [taylorbryant/next-starter-tailwind#66]
Hi Taylor!

Love this starter kit. Would you also consider adding a next+tailwind+emotion starter?

Let me know what you think! :)

**Comment by taylorbryant** [comment]
@theairbend3r That's a good idea! I'll look into that when I get some free time.

**Comment by taylorbryant** [comment]
Available here: https://github.com/zeit/next.js/tree/canary/examples/with-tailwindcss-emotion
